"""
Django settings for djTxiangmu project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cbol&(mop+uyo++kex^d$ufi5#ndl1pmg35#6ifj1-2h1q)in+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'account.User'
# app_name.Model_name(app的名字.Model的名字)
AUTH_USER_MODEL = 'account.User'#


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes', # 记录Django数据库模型信息
    'django.contrib.sessions',  #
    'django.contrib.messages', # 消息提示功能
    'django.contrib.staticfiles',  #  静态文件路径
    'apps.account',
    'apps.course',
    'apps.doc',
    'apps.news',
    'apps.one',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # 安全中间键 做有关安全认证（对请求头，请求的认证）
    'django.contrib.sessions.middleware.SessionMiddleware',  # 会话中间键 从会话中取session
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djTxiangmu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', #  指向后端模板引擎
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
# 将函数内置到模板中 https://docs.djangoproject.com/en/2.1/topics/templates/
            'builtins':['django.templatetags.static'],
        },
    },
]

WSGI_APPLICATION = 'djTxiangmu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default':{
    #     'ENGINE':'django.db.backends.sqlite3',
    #     'NAME':os.path.join(BASE_DIR,'db.sqlite3')
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',    #数据库引擎
        'NAME': 'djTx',                          #数据库名称
        'USER': 'root',                          #链接数据库的用户名
        'PASSWORD': 'qwe123',                    #链接数据库的密码
        'HOST': '127.0.0.1',                     #MySQL服务器的域名和ip地址,如保持默认，则为127.0.0.1
        'PORT': 3306,                            #端口，如保持默认，则为3306
    }
    # 'default':{
    #     'ENGINE':'django.db.backends.mysql',
    #     'OPTIONS':{
    #         'read_default_file':'utils/dbs/my.cnf'
    #     }
    # }
}

# 在settings.py文件中指定redis配置
CACHES = {
    'BACKEND':'django-redis.cache.RedisCache',
    'LOCATION':'redis://127.0.0.1:6379/0',
    'OPTIONS':{
        'CLIENT_CLASS':'django_redis.client.DefaultClient',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
MEDIA_ROOT = os.path.join(BASE_DIR,'static/media')